<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <XamlDebuggingInformation>True</XamlDebuggingInformation>
    <PlatformTarget>x64</PlatformTarget>
    <ErrorReport>prompt</ErrorReport>
    <BaseOutputPath>C:\Users\Msı\source\repos\PrimalEngine\MyGameEngineProject</BaseOutputPath>
    <PackageOutputPath></PackageOutputPath>
    <Configurations>DebugEditor;ReleaseEditor</Configurations>
    <Platforms>x64</Platforms>
  </PropertyGroup>

<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DebugEditor|x64'">
  <Optimize>True</Optimize>
</PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ReleaseEditor|x64'">
    <Optimize>False</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\PrimitiveMeshWindow\CheckerMap.png" />
    <None Remove="Resources\PrimitiveMeshWindow\PlaneTexture.png" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="EnvDTE80">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>8</VersionMajor>
      <Guid>1a31287a-4d7d-413e-8e32-3b374931bd89</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
    <COMReference Include="EnvDTE">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>8</VersionMajor>
      <Guid>80cc9f66-e7d8-4ddd-85b6-d9e6cd0e93e2</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>False</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\PrimitiveMeshWindow\CheckerMap.png" />
    <Resource Include="Resources\PrimitiveMeshWindow\PlaneTexture.png" />
  </ItemGroup>

</Project>